package com.migration.service.model.knowledgeCollection;

public enum NodeType {
		INTERFACE, ABSTRACTCLASS, CLASS, JAVAIMPLEMENTATION, FUNCTIONALITY, LIBRARY, RESOURCE, ENUM, ENTITY, INJECTEDEXTERNAL, LAYER


}
